// https://docs.cypress.io/api/introduction/api.html

describe('App Vue Test', () => {
  beforeEach(function() {
    cy.visit('http://localhost:8080')
  })

  it('Validate App component url', () => {
    // Validate App Div
    cy.get('#app') 
      .get('div')
      .should('have.class','container')
      .and('have.length',3)
      .get(".h1")
      .contains("Welcome to Tic Tac Toe Game")
      .get(".h2")
      .contains("1st Player is X")
      .get(".h3")
      .contains("2nd Player is O")
      .get(".h4")
      .contains("You are 1st player (X)")
      .get(".h5")
      .contains("Lets the game begin")
  })

  it('Validate Board component', () => {
      cy.get('table')
        .should('have.class','table table-bordered')
        .and('have.length',1)
        .get('tbody')
        .should('have.length',1)
        .and('not.have.class',undefined)
        .get('tr')
        .and('have.length',3)
        .get("#1")
        .and('have.length',1)
        .get("#2")
        .and('have.length',1)
        .get("#3")
        .and('have.length',1)
        .get('td')
        .and('have.length',9)
        .get("#A1")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#B1")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#C1")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#A2")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#B2")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#C2")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#A3")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#B3")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
        .get("#C3")
        .should('have.length',1)
        .and('have.attr','width','200')
        .and('have.attr','height','200')
  })

  it('Click Player X and O',() => {
    cy.get('#A1')
      .click()
      .children('img')
      .should('have.length',1)
      .and('have.attr','width','100')
      .and('have.attr','src')
      .and('contains','data:image/png')
      .get('#B1')
      .click()
      .children('img')
      .should('have.length',1)
      .and('have.attr','width','100')
      .and('have.attr','src')
      .and('contains','data:image/png')
  })
})
